---
- name: Ensure Helm is installed
  ansible.builtin.shell: |
    if ! command -v helm &>/dev/null; then
      curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    fi
  args:
    creates: /usr/local/bin/helm

## ansible controller needs it
# Ensure kubernetes.core collection is installed (if not already installed)
- name: Ensure kubernetes.core collection is installed
  ansible.builtin.command:
    cmd: ansible-galaxy collection install kubernetes.core
  register: install_k8s_collection
  failed_when: install_k8s_collection.rc != 0 and "'Requirement already satisfied' not in install_k8s_collection.stderr"
  changed_when: "'Requirement already satisfied' not in install_k8s_collection.stderr"
  tags:
    - always

## ansible controller needs it
- name: Ensure required Python libraries for Kubernetes are installed
  pip:
    name:
      - kubernetes
      - openshift
    state: present
