---
- name: Ensure required packages for Helm repo are installed
  ansible.builtin.apt:
    name:
      - curl
      - gpg
      - apt-transport-https
    state: present
    update_cache: yes

- name: Add Helm GPG key
  ansible.builtin.apt_key:
    url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    keyring: /usr/share/keyrings/helm.gpg
    state: present

- name: Add Helm repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
    state: present
    filename: helm-stable-debian

- name: Update apt cache after adding Helm repo
  ansible.builtin.apt:
    update_cache: yes

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: present

# Ensure kubernetes.core collection is installed (if not already installed)
## you dont need this is new multinode k3s cyverse.
- name: Ensure kubernetes.core collection is installed
  ansible.builtin.command:
    cmd: ansible-galaxy collection install kubernetes.core
  register: install_k8s_collection
  failed_when: install_k8s_collection.rc != 0 and "'Requirement already satisfied' not in install_k8s_collection.stderr"
  changed_when: "'Requirement already satisfied' not in install_k8s_collection.stderr"
  tags:
    - always
  when: run_kubernetes_core | default(false)

- name: Install python3-venv if not already installed
  apt:
    name: python3-venv
    state: present
  when: run_kubernetes_core | default(false)

- name: Create a Python virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv /temp/virtualenv/venv
    creates: /temp/virtualenv/venv/bin/activate
  become: yes
  when: run_kubernetes_core | default(false)

- name: Install Kubernetes Python package in virtual environment
  pip:
    name: kubernetes
    virtualenv: /temp/virtualenv/venv
    virtualenv_python: /usr/bin/python3
  when: run_kubernetes_core | default(false)

- name: Ensure the correct Python interpreter for Ansible
  ansible.builtin.set_fact:
    ansible_python_interpreter: /temp/virtualenv/venv/bin/python
  when: run_kubernetes_core | default(false)
