---
- name: Ensure Helm is installed
  ansible.builtin.shell: |
    if ! command -v helm &>/dev/null; then
      curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    fi
  args:
    creates: /usr/local/bin/helm

# Ensure kubernetes.core collection is installed (if not already installed)
## you dont need this is new multinode k3s cyverse.
- name: Ensure kubernetes.core collection is installed
  ansible.builtin.command:
    cmd: ansible-galaxy collection install kubernetes.core
  register: install_k8s_collection
  failed_when: install_k8s_collection.rc != 0 and "'Requirement already satisfied' not in install_k8s_collection.stderr"
  changed_when: "'Requirement already satisfied' not in install_k8s_collection.stderr"
  tags:
    - always
  when: run_kubernetes_core | default(false)

- name: Install python3-venv if not already installed
  apt:
    name: python3-venv
    state: present
  when: run_kubernetes_core | default(false)

- name: Create a Python virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv /temp/virtualenv/venv
    creates: /temp/virtualenv/venv/bin/activate
  become: yes
  when: run_kubernetes_core | default(false)

- name: Install Kubernetes Python package in virtual environment
  pip:
    name: kubernetes
    virtualenv: /temp/virtualenv/venv
    virtualenv_python: /usr/bin/python3
  when: run_kubernetes_core | default(false)

- name: Ensure the correct Python interpreter for Ansible
  ansible.builtin.set_fact:
    ansible_python_interpreter: /temp/virtualenv/venv/bin/python
  when: run_kubernetes_core | default(false)
