---

- name: Install iptables-persistent
  ansible.builtin.apt:
    update_cache: true
    state: present
    name:
      - "{{ (ansible_lsb.release | int == 12) | ternary('nftables', 'iptables-persistent') }}"

- name: Enable and start nftables
  ansible.builtin.systemd:
    service: "{{ (ansible_lsb.release | int == 12) | ternary('nftables', 'iptables') }}"
    enabled: true
    state: started
    daemon_reload: true
