---

- name: Install iptables
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  tags:
    - firewall

- name: Add firewall rules
  # when: check_for_comment.changed
  ansible.builtin.blockinfile:
    # insertafter: "# Kubernetes"
    insertafter: "-A INPUT -j KUBE-FIREWALL"
    marker: "## {mark} Kubernetes"
    # path: /etc/sysconfig/iptables
    path: /etc/iptables/rules.v4
    block: |
      *filter
      :INPUT DROP
      :FORWARD ACCEPT
      :OUTPUT ACCEPT
      -A INPUT -m state --state NEW,ESTABLISHED -m tcp -p tcp --dport 22 -j ACCEPT -m comment --comment "access with ssh"
      -A INPUT -m state --state NEW -m tcp -p tcp --dport 6443 -j ACCEPT -m comment --comment "kube-apiserver access"
      -A INPUT -m state --state NEW -m tcp -p tcp --dport 2379:2380 -j ACCEPT -m comment --comment "etcd"
      -A INPUT -m state --state NEW -m tcp -p tcp --dport 10250 -j ACCEPT -m comment --comment "kubelet api"
      -A INPUT -m state --state NEW -m tcp -p tcp --dport 10251 -j ACCEPT -m comment --comment "kube-scheduler api"
      -A INPUT -m state --state NEW -m tcp -p tcp --dport 10252 -j ACCEPT -m comment --comment "kube-controller-manager api"
      -A INPUT -m state --state NEW -m tcp -p tcp --dport 6783 -j ACCEPT -m comment --comment "weavenet tcp"
      -A INPUT -m state --state NEW -m tcp -p tcp --dport 30000:32767 -j ACCEPT
      -A INPUT -m state --state NEW -m udp -p udp --dport 6783:6784 -j ACCEPT -m comment --comment "weavenet udp"
      -A INPUT -p icmp -m state --state RELATED,ESTABLISHED -j ACCEPT -m comment --comment "ping"
      -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT -m comment --comment "allow return traffic"
      COMMIT
  tags:
    - firewall
  notify:
    - Save firewall-rules
    - Reload firewall-rules
      # -A INPUT -p udp -m udp --sport 53 -m state --state ESTABLISHED -j ACCEPT -m comment --comment "dns query"
      # -A INPUT -p tcp -m tcp --sport 53 -m state --state ESTABLISHED -j ACCEPT -m comment --comment "dns query"
      # -A INPUT -p tcp -m tcp --sport 443 -m state --state ESTABLISHED -j ACCEPT -m comment --comment "https download"
      # -A INPUT -p tcp -m tcp --sport 80 -m state --state ESTABLISHED -j ACCEPT -m comment --comment "http download"

# - name: Save firewall-rules
#   ansible.builtin.shell:
#     cmd: "/usr/sbin/netfilter-persistent save"
#     creates: '/etc/iptables/rules.v4'
#   tags:
#     - firewall
#   notify:
#     - Reload firewall

- name: Change input policy to DROP
  ansible.builtin.replace:
    path: /etc/iptables/rules.v4
    regexp: '(\*filter\n)(:INPUT) ACCEPT'
    replace: '\1\2 DROP'
  tags:
    - firewall
  notify:
    - Save firewall-rules
    - Reload firewall-rules
