---
- name: Copy Cilium values.yaml to the target host
  copy:
    src: cilium-values.yaml
    dest: /tmp/cilium-values.yaml

- name: Install Cilium using Helm chart
  become: yes
  become_user: root
  shell: |
    helm install cilium cilium/cilium --namespace kube-system --create-namespace --version "{{ cilium_version }}" -f /tmp/cilium-values.yaml
  args:
    chdir: $HOME
