---
- name: Install & configure cert
  # hosts: ~.*-vice-haproxy\..*
  hosts: "{{ var_hosts | default('~.*-vice-haproxy\\..*') }}"
  gather_facts: true
  become: true
  roles:
    - role: cert_bot
      domain: vice.cyverse.at
      cert_mail: "foo.bar@mailinator.com"
      tls_pem_path: "/etc/ssl/certs/{{ domain }}.pem"
