---
- name: Run destroy command
  hosts: k8s
  become: yes
  tasks:
    - name: Run kubeadm reset
      command: /usr/bin/kubeadm reset --force
      ignore_errors: yes

- name: Remove Kubernetes packages
  hosts: k8s
  become: yes
  tasks:
    - name: Remove the kube* packages
      apt:
        name: ['kubeadm', 'kubectl', 'kubelet', 'kubernetes-cni', 'kube*']
        state: absent
      ignore_errors: yes

- name: Remove files
  hosts: k8s
  become: yes
  tasks:
    - name: Remove .kube directory
      shell: rm -rf ~/.kube
    - name: Remove /etc/kubernetes
      shell: rm -rf /etc/kubernetes
    - name: Remove /opt/cni
      shell: rm -rf /opt/cni
    - name: Remove weave generated file
      shell: rm -rf ~/pod_setup.txt
    - name: Remove /etc/kubernetes/pki
      shell: rm -rf /etc/kubernetes/pki
    - name: Remove /var/lib/kubelet
      shell: rm -rf /var/lib/kubelet
    - name: Remove /var/lib/cni
      shell: rm -rf /var/lib/cni
    - name: Remove /etc/cni
      shell: rm -rf /etc/cni
    - name: Remove /etc/kubernetes/manifests
      shell: rm -rf /etc/kubernetes/manifests
    - name: Remove /etc/systemd/system/kubelet.service.d
      shell: rm -rf /etc/systemd/system/kubelet.service.d

- name: Uninstall and disable Containerd
  hosts: k8s
  become: yes
  tasks:
    - name: Remove the Containerd package
      apt:
        name: ['containerd', 'containerd.io']
        state: absent
    - name: Stop the Containerd service
      service:
        name: containerd
        state: stopped
    - name: Disable the Containerd service
      systemd:
        name: containerd
        enabled: no

- name: Remove /etc/containerd
  hosts: k8s
  become: yes
  tasks:
    - name: Remove containerd directory
      shell: rm -rf /etc/containerd

- name: Ensure kubelet is stopped and disabled
  hosts: k8s
  become: yes
  tasks:
    - name: Stop kubelet service
      service:
        name: kubelet
        state: stopped
    - name: Disable kubelet service
      systemd:
        name: kubelet
        enabled: no

- name: Run apt autoclean and autoremove
  hosts: k8s
  become: yes
  tasks:
    - name: Run apt autoclean
      ansible.builtin.apt:
        autoclean: yes
    - name: Run apt autoremove
      ansible.builtin.apt:
        autoremove: yes

- name: Update and upgrade system packages
  hosts: k8s
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
    - name: Upgrade all packages
      apt:
        upgrade: dist
