---
- name: run destroy command
  hosts: k8s
  become: yes
  tasks:
    - name: run destroy.sh
      command: /usr/bin/kubeadm reset --force
      ignore_errors: yes

- name: remmove packages
  hosts: k8s
  become: yes
  tasks:
    - name: Remove the kube*
      apt:
        name: ['kubeadm', 'kubectl', 'kubelet', 'kubernetes-cni', 'kube*']
        state: absent
      ignore_errors: yes

- name: Remove files
  hosts: k8s
  become: yes
  tasks:
    - name: Remove .kube
      shell: rm -rf ~/.kube
    - name: Remove /etc/kubernetes
      shell: rm -rf /etc/kubernetes
    - name: Remove /opt/cni
      shell: rm -rf /opt/cni

- name: Uninstall and Disable Containerd
  hosts: k8s
  become: yes
  tasks:
    - name: Remove the Containerd package
      apt:
        name: ['containerd', 'containerd.io']
        state: absent

    - name: Stop the Containerd service
      service:
        name: containerd
        state: stopped

    - name: Disable the Containerd service
      systemd:
        name: containerd
        enabled: no

- name: Remove /etc/containerd
  hosts: k8s
  become: yes
  tasks:
    - name: Remove containerd file
      shell: rm -rf /etc/containerd

- name: Run apt autoclean and autoremove
  hosts: k8s
  become: yes
  tasks:
    - name: Run apt autoclean
      command: apt autoclean

    - name: Run apt autoremove with timeout
      command: apt autoremove
      async: 600 # Run for a maximum of 10 minutes (600 seconds)
      poll: 5
      register: autoremove_result

    - name: Check result of apt autoremove
      async_status:
        jid: "{{ autoremove_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 10

      
- name: Update and upgrade system packages
  hosts: k8s
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
