---
- hosts: localhost
  become: yes
  gather_facts: true
  roles:
    - role: etcd_certificates # create ca and certs for etcd node

- hosts: etcd-nodes
  become: yes
  gather_facts: true
  roles:
    - role: external-etcd
