---

- name: Install HAProxy 01
  hosts: haproxy01
  gather_facts: true
  become: true
  roles:
    - role: haproxy01

  # Vars newly added
  vars:
    domain: cyverse.at
    tls_pem_path: "/etc/ssl/certs/{{ domain }}.pem"

  tasks:
    - name: reload haproxy
      systemd:
        daemon_reload: true
        service: haproxy
        state: reloaded
        enabled: true
