---
- name: Configure iptables for Kubernetes
  hosts: k8s
  gather_facts: true
  become: true
  # roles:
  #   - iptables-config

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled
  hosts: k8s
  gather_facts: true
  become: true

  tasks:

    - name: Grab the swap space used (in megabytes)
      ansible.builtin.shell: >
        set -o pipefail &&
        free -m |
        awk '/Swap/{print $2}'
      register: swap_used
      failed_when: false
      check_mode: false
      # changed_when: snap_installed_result.rc != 0
      changed_when: (swap_used.stdout_lines[0] | int) > 0
      args:
        executable: /bin/bash

    - name: Turn off swap
      ansible.builtin.shell: "swapoff -a"
      when: (swap_used.stdout_lines[0] | int) > 0

    - name: Remove Swap Entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: "^/dev/.*swap.*"

- name: Disable iptable/nftables
  hosts: k8s
  gather_facts: true
  become: true
    - name: Stop and disable nftables service
      systemd:
        name: nftables
        enabled: no
        state: stopped
      ignore_errors: yes  # Ignore errors if nftables is not installed or not running

    - name: Stop and disable iptables service
      systemd:
        name: iptables
        enabled: no
        state: stopped
      ignore_errors: yes  # Ignore errors if iptables is not installed or not running
