---
- name: Configure kube-apiserver haproxy
  hosts: kube-apiserver-haproxy
  become: true
  tasks:
    - name: Put SELinux in permissive mode
      ansible.posix.selinux:
        policy: "{{ (ansible_facts['distribution'] == 'Debian') | ternary('default', 'targeted') }}"
        state: permissive
  roles:
    - kube-apiserver-haproxy-installer
  tags:
    - haproxy

- name: Install stuff
  hosts: k8s
  gather_facts: true
  become: true

  pre_tasks:
    - name: Install socat and runc
      ansible.builtin.apt:
        name:
          - socat
          - runc
        state: present
        update_cache: yes

  roles:
    - role: githubixx.containerd
      containerd_config: |
        version = 3
        [plugins."io.containerd.cri.v1"]
          sandbox_image = "registry.k8s.io/pause:3.10"
          [plugins.'io.containerd.cri.v1.runtime']
            [plugins.'io.containerd.cri.v1.runtime'.containerd]
              default_runtime_name = 'runc'
              [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes]
                [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.runc]
                  runtime_type = 'io.containerd.runc.v2'
                  [plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.runc.options]
                    BinaryName = '/usr/sbin/runc'
                    SystemdCgroup = true
            [plugins.'io.containerd.cri.v1.runtime'.cni]
              bin_dir = '/opt/cni/bin'
              conf_dir = '/etc/cni/net.d'
    - role: kubeadm-installer

  tasks:
    - name: Start containerd
      ansible.builtin.systemd:
        daemon_reload: true
        service: containerd
        state: started
        enabled: true

    - name: Start kubelet
      ansible.builtin.systemd:
        daemon_reload: true
        service: kubelet
        state: started
        enabled: true
