---
- name: Configure kube-apiserver haproxy
  hosts: kube-apiserver-haproxy
  # gather_facts: true
  become: true
  tasks:
    - name: Put SELinux in permissive mode
      ansible.posix.selinux:
        policy: "{{ (ansible_facts['distribution'] == 'Debian') | ternary('default', 'targeted') }}"
        # policy: targeted
        state: permissive
  roles:
    - kube-apiserver-haproxy-installer
  tags:
    - haproxy

- name: Install stuff
  hosts: k8s
  gather_facts: true
  become: true

  pre_tasks:
    - name: Install socat
      # ansible.builtin.yum:
      ansible.builtin.package:
        name: socat
        state: present

  roles:
    - githubixx.containerd
    # - docker-installer # todo remove actual docker installs
    - kubeadm-installer

  tasks:
    - name: Start containerd
      ansible.builtin.systemd:
        daemon_reload: true
        service: containerd
        state: started
        enabled: true

    - name: Start kubelet
      ansible.builtin.systemd:
        daemon_reload: true
        service: kubelet
        state: started
        enabled: true
