---

roles:
    - name: githubixx.containerd
      version: "0.15.0+2.1.3"
    - name: githubixx.cfssl
      src: https://github.com/githubixx/ansible-role-cfssl.git
      version: 8.3.0+1.6.5

collections:
    - name: community.general
      version: ">=6.4.0"



