---
- name: Configure Kubernetes and Docker Repositories
  hosts: all
  become: true
  tasks:

    - name: Download Docker GPG key
      get_url:
        url: "https://download.docker.com/linux/debian/gpg"
        dest: "/usr/share/keyrings/docker-archive-keyring.gpg"

    - name: Add Docker repository to APT sources.list.d
      lineinfile:
        dest: "/etc/apt/sources.list.d/docker.list"
        line: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        create: yes


    - name: Add Kubernetes repository
      shell: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
      args:
        executable: /bin/bash

    - name: Download Kubernetes GPG key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        executable: /bin/bash

    - name: Add Docker GPG key to APT keyring
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Create Docker repository configuration file
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        create: yes

    - name: Update APT package lists
      apt:
        update_cache: yes