---
- name: Install HAProxy on VICE proxy
  hosts: outward-facing-proxy
  gather_facts: true
  become: true
  roles:
    - { role: vice-haproxy-installer }

  # Vars newly added
  vars:
    domain: vice.cyverse.at
    regsub: '\.vice\.cyverse\.at$,'
    tls_pem_path: "/etc/ssl/certs/{{ domain }}.pem"

  tasks:
    - name: reload haproxy
      systemd:
        daemon_reload: true
        service: haproxy
        state: reloaded
        enabled: true
