---
- name: Add Gitlab Runner Helm repository
  ansible.builtin.command: helm repo add gitlab https://charts.gitlab.io
  register: gitlab_runner
  changed_when: "'has been added' in gitlab_runner.stdout or 'already exists' in gitlab_runner.stderr"

- name: Update Helm repositories
  ansible.builtin.command: helm repo update

- name: Ensure directory for Gitlab Runner values exists
  ansible.builtin.file:
    path: /etc/kubernetes/gitlab-runner
    state: directory
    mode: '0755'

- name: Render Gitlab Runner {{ gitlab_runner_a }} values file with template
  ansible.builtin.template:
    src: values.yaml.j2
    dest: /etc/kubernetes/gitlab-runner/gitlab-runner-a-values.yaml
    mode: '0644'

- name: Install or upgrade Gitlab Runner {{ gitlab_runner_a }} via Helm
  ansible.builtin.command: >
    helm upgrade --install {{ gitlab_runner_a }} gitlab/gitlab-runner
    --namespace gitlab-runner
    --create-namespace
    -f /etc/kubernetes/gitlab-runner/gitlab-runner-a-values.yaml

# TODO
# - name: Wait for Gitlab Runner pods to be ready

