---

- name: create the ArgoCD namespace
  kubernetes.core.k8s:
    name: "argocd"
    state: present
    kind: namespace
    api_version: v1

- name: Apply Kyverno ClusterPolicy to prevent default project in Argo CD Applications
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: kyverno.io/v1
      kind: ClusterPolicy
      metadata:
        name: application-prevent-default-project
        annotations:
          policies.kyverno.io/title: Prevent Use of Default Project
          policies.kyverno.io/category: Argo
          policies.kyverno.io/severity: medium
          policies.kyverno.io/subject: Application
          policies.kyverno.io/description: >
            This policy prevents the use of the default project in an Argo CD Application.
      spec:
        validationFailureAction: Enforce
        background: true
        rules:
          - name: disallow-default-project
            match:
              any:
                - resources:
                    kinds:
                      - Application
            preconditions:
              all:
                - key: "{{ request.operation || 'BACKGROUND' }}"
                  operator: NotEquals
                  value:
                    - CREATE
                    - UPDATE
            validate:
              message: "The default project may not be used in an Argo CD Application."
              pattern:
                spec:
                  project: "!default"



- name: Apply ArgoCD Vault Plugin ConfigManagementPlugin in argocd ns
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'cmp_configmap.yaml') | from_yaml_all }}"

- name: Create required secret for Argo CD Vault Plugin
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'argocd_vault_plugin_secret.yaml') | from_yaml_all }}"

- name: Create required github app credentials
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        annotations:
          managed-by: argocd.argoproj.io
        labels:
          argocd.argoproj.io/secret-type: repository
        name: "{{ argocd_github_app_secret }}"
        namespace: argocd
      type: Opaque
      data:
        githubAppID: "{{ argocd_repositories_default_appId | b64encode }}"
        githubAppInstallationID: "{{ argocd_repositories_default_installationId | b64encode }}"
        type: "{{ argocd_repositories_default_type | b64encode }}"
        url: "{{ argocd_repositories_default_url | b64encode }}"
        githubAppPrivateKey: "{{ argocd_repositories_default_privateKey }}"
        # project: dev


# helm deplyment
- name: Add Argocd Helm repository
  ansible.builtin.command: helm repo add argo https://argoproj.github.io/argo-helm
  register: add_argocd_repo
  changed_when: "'has been added' in add_argocd_repo.stdout or 'already exists' in add_argocd_repo.stderr"

- name: Update Helm repositories
  ansible.builtin.command: helm repo update

- name: Ensure directory for Argocd values exists
  ansible.builtin.file:
    path: /etc/kubernetes/argocd
    state: directory
    mode: '0755'

- name: Render Argocd values file with template
  ansible.builtin.template:
    src: values.yaml.j2
    dest: /etc/kubernetes/argocd/argocd-values.yaml
    mode: '0644'

- name: Install or upgrade Argocd via Helm
  ansible.builtin.command: >
    helm upgrade --install argocd argo/argo-cd
    --namespace argocd
    --create-namespace
    --version {{ argocd_helm_version }}
    -f /etc/kubernetes/argocd/argocd-values.yaml

# - name: Wait for ArgoCD pods to be ready
#   ansible.builtin.shell: |
#     kubectl wait --for=condition=Ready pod \
#       -n argocd \
#       -l app.kubernetes.io/component=repo-server
#       --timeout=300s
#   retries: 3
#   delay: 10
#   register: argocd_wait
#   until: argocd_wait.rc == 0
