---

# NOTE: In Debian11 selinux seems to be disabled by default
#
- name: Add repo key
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
    state: present

- name: Add repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    filename: kubernetes
    state: present
    update_cache: yes

- name: Add some packages
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - kubelet=1.28.2-00
      - kubeadm=1.28.2-00
      - kubectl=1.28.2-00
