---

# NOTE: In Debian11 selinux seems to be disabled by default
#

- name: Ensure /tmp has correct permissions
  ansible.builtin.file:
    path: /tmp
    mode: '1777'
    state: directory

- name: add Kubernetes apt-key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/{{ kube_version }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
    force: true

- name: add Kubernetes' APT repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/{{ kube_version }}/deb/ /"
    state: present
    update_cache: yes

- name: Add some packages
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - "kubelet"
      - "kubeadm"
      - "kubectl"
