---

# NOTE: In Debian11 selinux seems to be disabled by default
#
- name: Add Kubernetes apt repository key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    state: present

- name: Add Kubernetes apt repository
  ansible.builtin.copy:
    content: 'deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /'
    dest: /etc/apt/sources.list.d/kubernetes.list

- name: Add some packages
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - kubelet=1.28.2-00
      - kubeadm=1.28.2-00
      - kubectl=1.28.2-00
