---

- name: Install snapd
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Copy k8s.conf
  ansible.builtin.copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: "0644"

- name: Set IP forwarding to 1
  ansible.posix.sysctl:
    name: "net.ipv4.ip_forward"
    value: 1
    state: present

- name: Add the dummy module and make sure it is loaded after reboots
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  with_items:
    - "br_netfilter"
    - "overlay"

# NOTE no idea what this should doing
# - name: sysctl --system
#   shell: sysctl --system
