---

- name: SELinux permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: disabled
    # state: permissive
  notify:
    - Reboot and wait

- name: Setup kubernetes yum repo
  ansible.builtin.copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: "0644"

- name: Install packages for Rocky
  when:
    - ansible_distribution == "Rocky"
    - ansible_distribution_major_version | int > 8
  block:
    - name: Add ip_tables kernel module
      community.general.modprobe:
        name: ip_tables
        state: present
        # params: 'numdummies=2'
        persistent: present
    # - name: Install epel
    #   ansible.builtin.yum:
    #     name:
    #       - epel-release
    # - name: Install iptables
    #   ansible.builtin.yum:
    #     name:
    #       - iptables-legacy

- name: Install kube{let,adm,ctl}
  ansible.builtin.yum:
    name:
      - "kubelet={{ kube_x_version }}"
      - "kubeadm={{ kube_x_version }}"
      - "kubectl={{ kube_x_version }}"
    state: present
