apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: "argocd"
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true

      # Note: this command is run _before_ anything is done, therefore the logic is to check
      # if this looks like a Kustomize bundle
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml

      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate -"

      lockRepo: false
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata: 
      name: argocd-vault-plugin
    spec: 
      allowConcurrency: true

      discover: 
        find: 
          command: 
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."

      generate: 
        command: 
          - argocd-vault-plugin
          - generate
          - "."

      lockRepo: false
  avp-helm-inline-values.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm-inline
    spec:
      allowConcurrency: true

      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml'"

      # Inline Helm values via env var HELM_VALUES
      generate:
        command:
          - bash
          - "-c"
          - |
            helm dependency build . >/dev/null 2>&1 || true
            helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo "$ARGOCD_ENV_HELM_VALUES") . |
            argocd-vault-plugin generate -

      lockRepo: false
  avp-helm-files.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm-files
    spec:
      allowConcurrency: true

      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml'"

      # helm values via private git repo using SSH authentication
      generate:
        command:
          - bash
          - "-c"
          - |
            helm dependency build . >/dev/null 2>&1 || true
            export GITHUB_APP_ID=$GITHUB_APP_ID
            export GITHUB_INSTALLATION_ID=$GITHUB_INSTALLATION_ID
            export GITHUB_APP_PRIVATE_KEY="$GITHUB_APP_PRIVATE_KEY"
            
            # Strip '.git' from the end of the repo URL if it exists
            REPO_URL=$(echo $ARGOCD_ENV_HELM_VALUES_REPO | sed 's/\.git$//')
            REPO_NAME=$(basename $REPO_URL)  # Extract repo name from URL

            # Clone the repository using SSH
            if [[ -n "$ARGOCD_ENV_HELM_VALUES_BRANCH" ]]; then
              python3 -c "from github import GithubIntegration, Auth; import os, subprocess; url=os.environ['ARGOCD_ENV_HELM_VALUES_REPO'].rstrip('/').replace('.git', ''); repo='/'.join(url.split('/')[-2:]); branch=os.environ.get('ARGOCD_ENV_HELM_VALUES_BRANCH'); auth=Auth.AppAuth(int(os.environ['GITHUB_APP_ID']), os.environ['GITHUB_APP_PRIVATE_KEY']); gi=GithubIntegration(auth=auth); token=gi.get_access_token(int(os.environ['GITHUB_INSTALLATION_ID'])).token; cmd=['git','clone',f'https://x-access-token:{token}@github.com/{repo}.git']; cmd.extend(['-b', branch] if branch else []); subprocess.run(cmd)"
            else
              python3 -c "from github import GithubIntegration, Auth; import os, subprocess; url=os.environ['ARGOCD_ENV_HELM_VALUES_REPO'].rstrip('/').replace('.git', ''); repo='/'.join(url.split('/')[-2:]); auth=Auth.AppAuth(int(os.environ['GITHUB_APP_ID']), os.environ['GITHUB_APP_PRIVATE_KEY']); gi=GithubIntegration(auth=auth); token=gi.get_access_token(int(os.environ['GITHUB_INSTALLATION_ID'])).token; subprocess.run(['git','clone',f'https://x-access-token:{token}@github.com/{repo}.git'])"
            fi

            # Now, use the repo name to prepend it to the Helm values directory path
            FULL_HELM_VALUES_DIR="$REPO_NAME/$ARGOCD_ENV_HELM_VALUES_DIR"
            
            # Run Helm template generation
            helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f $FULL_HELM_VALUES_DIR/values.yaml . |
            argocd-vault-plugin generate -

      lockRepo: false
---


# https://pygithub.readthedocs.io/en/stable/examples/Authentication.html#app-authentication