apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-custom-docker-images
  namespace: argocd
type: Opaque
data:
  githubAppID: {{ argocd_repositories_default_appId | b64encode }}
  githubAppInstallationID: {{ argocd_repositories_default_installationId | b64encode }}
  githubAppPrivateKey: {{ argocd_repositories_default_privateKey | b64encode }}
  type: git
  url: {{ argocd_repositories_default_url | b64encode }}
