---

- name: create the {{ argocd_image_updater_namespace }} namespace if not exists
  kubernetes.core.k8s:
    name: "{{ argocd_image_updater_namespace }}"
    state: present
    kind: namespace
    api_version: v1

- name: Add Argocd Helm repository
  ansible.builtin.command: helm repo add argo https://argoproj.github.io/argo-helm
  register: add_argocd_repo
  changed_when: "'has been added' in add_argocd_repo.stdout or 'already exists' in add_argocd_repo.stderr"

- name: Update Helm repositories
  ansible.builtin.command: helm repo update

- name: Ensure directory for Argocd Image updater values exists
  ansible.builtin.file:
    path: /etc/kubernetes/argocd-image
    state: directory
    mode: '0755'

- name: Render Argocd Image updater values file with template
  ansible.builtin.template:
    src: values.yaml.j2
    dest: /etc/kubernetes/argocd-image/argocd-image-values.yaml
    mode: '0644'
    force: yes

- name: Install or upgrade Argocd via Helm
  ansible.builtin.command: >
    helm upgrade --install argocd-image-updater argo/argocd-image-updater
    --namespace argocd
    --create-namespace
    --version {{ argocd_image_updater_helm_version }}
    -f /etc/kubernetes/argocd-image/argocd-image-values.yaml
