---
- name: Add NFS Provisioner Helm repository
  ansible.builtin.command: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  register: nfs_provisioner_repo
  changed_when: "'has been added' in nfs_provisioner_repo.stdout or 'already exists' in nfs_provisioner_repo.stderr"

- name: Update Helm repositories
  ansible.builtin.command: helm repo update

- name: Ensure directory for NFS Provisioner values exists
  ansible.builtin.file:
    path: /etc/kubernetes/nfs-provisioner
    state: directory
    mode: '0755'

- name: Render NFS Provisioner values file with template
  ansible.builtin.template:
    src: values.yaml.j2
    dest: /etc/kubernetes/nfs-provisioner/nfs-provisioner-values.yaml
    mode: '0644'

- name: Install or upgrade NFS Provisioner via Helm
  ansible.builtin.command: >
    helm upgrade --install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    --namespace nfs-provisioner
    --create-namespace
    -f /etc/kubernetes/nfs-provisioner/nfs-provisioner-values.yaml

- name: Wait for NFS Provisioner pods to be ready
  ansible.builtin.shell: |
    kubectl wait \
      --for=condition=Ready \
      pods -n nfs-provisioner \
      -l app=nfs-subdir-external-provisioner \
      --timeout=300s
  retries: 3
  delay: 10
  register: nfs_wait
  until: nfs_wait.rc == 0
