---
- name: Update the OS
  package:
    name: '*'
    state: latest


- name: Install necessary packages
  package:
    name: openssl
    state: present

- name: Create CA directories
  file:
    path: "{{ ca_directory }}/{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - private
    - certs
    - newcerts
    - crl

- name: Create index.txt and serial files
  copy:
    content: "{{ item }}"
    dest: "{{ ca_directory }}/{{ item }}"
  loop:
    - { name: 'index.txt', content: '' }
    - { name: 'serial', content: '01' }

- name: Generate CA private key without passphrase
  command: >
    openssl genpkey
    -algorithm RSA
    -out {{ ca_key_file }}
  args:
    creates: "{{ ca_key_file }}"

- name: Generate CA root certificate
  command: >
    openssl req
    -x509
    -new
    -key {{ ca_key_file }}
    -sha256
    -days {{ ca_validity_days }}
    -out {{ ca_cert_file }}
    -subj "/C={{ ca_country }}/ST={{ ca_state }}/L={{ ca_locality }}/O={{ ca_organization }}/OU={{ ca_organizational_unit }}/CN={{ ca_name }}/emailAddress={{ ca_email }}"
  args:
    creates: "{{ ca_cert_file }}"
