---
# this is temp- should find a way to avoid
- name: create the "{{ lcalyze_ns }}" namespace
  kubernetes.core.k8s:
    name: "{{ lcalyze_ns }}"
    state: present
    kind: namespace
    api_version: v1

- name: create the harbor json file
  ansible.builtin.copy:
    dest: "harbor_login.json"
    content: "{}"

- name: create the harbor dockerconfigjson content manually
  ansible.builtin.set_fact:
    dockerconfigjson_content: |
      {
        "auths": {
          "{{ harbor_url }}": {
            "auth": "{{ (harbor_robot_name + ':' + harbor_robot_secret) | b64encode }}"
          }
        }
      }

- name: Create the harbor image pull secret
  kubernetes.core.k8s:
    state: present
    force: true
    definition:
      apiVersion: v1
      data:
        .dockerconfigjson: "{{ dockerconfigjson_content | to_json | b64encode }}"
      kind: Secret
      metadata:
        name: "{{ image_pull_secret_name }}"
        namespace: "{{ item }}"
      type: "kubernetes.io/dockerconfigjson"
  with_items:
    - "{{ lcalyze_ns }}"

- name: remove the tempfile for the harbor login json
  ansible.builtin.file:
    path: harbor_login.json
    state: absent
