ingressController:
  enabled: false  # Cilium will not manage ingress; you're using nginx

cni:
  install: true
  chainingMode: none
  confPath: /etc/cni/net.d
  binPath: /opt/cni/bin

# -- Configure the kube-proxy replacement in Cilium BPF datapath
# Valid options are "true" or "false".
# ref: https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/
kubeProxyReplacement: "false"


hubble:
  ui:
    enabled: true
    ingress:
      enabled: true
      className: nginx
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      hosts:
        - hubble.lb.cyverse.at
      path: /
      pathType: Prefix
      tls: []  # You can keep this empty because TLS is handled externally

  relay:
    # -- Enable Hubble Relay (requires hubble.enabled=true)
    enabled: true

debug:
  enabled: false
  verbose: ""