---
- name: "Copy destroy.sh scipt on the remote hosts"
  copy:
    src: destroy.sh
    dest: /root/
    mode: 0755

- name: "Execute the script"
  command: sh ~/destroy.sh
  register: status
- debug:
   var: status.stdout_lines

- name: Remove Shell Script
  file:
   path: /root/destroy.sh
   state: absent

