---
- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Generate haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
