---
- name: Ensure cfssl is present
  include_role:
    name: githubixx.cfssl

- name: Ensure certificate directory
  file:
    path: "{{ source_cert_dir }}"
    state: directory
    mode: '0755'

- name: Create CA configuration file
  copy:
    src: ca-config.json
    dest: "{{ source_cert_dir }}/ca-config.json"

- name: Create CA CSR file
  copy:
    src: ca-csr.json
    dest: "{{ source_cert_dir }}/ca-csr.json"

- name: Generate CA certificate
  shell: |
    cfssl gencert -initca {{ source_cert_dir }}/ca-csr.json | cfssljson -bare {{ source_cert_dir }}/ca
  args:
    creates: "{{ source_cert_dir }}/ca.pem"

- name: Generate etcd CSR file
  template:
    src: etcd-csr.json.j2
    dest: "{{ source_cert_dir }}/etcd-csr.json"

- name: Generate etcd certificate
  shell: |
    cfssl gencert -ca={{ source_cert_dir }}/ca.pem -ca-key={{ source_cert_dir }}/ca-key.pem -config={{ source_cert_dir }}/ca-config.json -profile=etcd {{ source_cert_dir }}/etcd-csr.json | cfssljson -bare {{ source_cert_dir }}/etcd
  args:
    creates: "{{ source_cert_dir }}/etcd.pem"
