---
- name: Ensure cfssl is present
  include_role:
    name: githubixx.cfssl

- name: Ensure certificate directory
  file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0755'

- name: Create CA configuration file
  copy:
    src: ca-config.json
    dest: "{{ cert_dir }}/ca-config.json"

- name: Create CA CSR file
  copy:
    src: ca-csr.json
    dest: "{{ cert_dir }}/ca-csr.json"

- name: Generate CA certificate
  shell: |
    cfssl gencert -initca {{ cert_dir }}/ca-csr.json | cfssljson -bare {{ cert_dir }}/ca
  args:
    creates: "{{ cert_dir }}/ca.pem"

- name: Generate etcd CSR file
  template:
    src: etcd-csr.json.j2
    dest: "{{ cert_dir }}/etcd-csr.json"

- name: Generate etcd certificate
  shell: |
    cfssl gencert -ca={{ cert_dir }}/ca.pem -ca-key={{ cert_dir }}/ca-key.pem -config={{ cert_dir }}/ca-config.json -profile=etcd {{ cert_dir }}/etcd-csr.json | cfssljson -bare {{ cert_dir }}/etcd
  args:
    creates: "{{ cert_dir }}/etcd.pem"

##################################################

# - name: Copy CA certificate to etcd nodes
#   copy:
#     src: ca.pem
#     dest: "{{ cert_dir }}/ca.pem"
#   delegate_to: "{{ item }}"
#   with_items: "{{ groups['etcd-nodes'] }}"

# - name: Copy etcd certificate to etcd nodes
#   copy:
#     src: etcd.pem
#     dest: "{{ cert_dir }}/etcd.pem"
#   delegate_to: "{{ item }}"
#   with_items: "{{ groups['etcd-nodes'] }}"

# - name: Copy etcd key to etcd nodes
#   copy:
#     src: etcd-key.pem
#     dest: "{{ cert_dir }}/etcd-key.pem"
#   delegate_to: "{{ item }}"
#   with_items: "{{ groups['etcd-nodes'] }}"
