---
ca_name: "etcd cluster"
ca_country: "AU"
ca_state: "Styre"
ca_locality: "Graz"
ca_organization: "TU Graz"
ca_organizational_unit: "IT"
ca_email: "mojib.wali@tugraz.at"
ca_directory: "/etc/ssl/myca"
ca_key_file: "{{ ca_directory }}/private/myca.key"
ca_cert_file: "{{ ca_directory }}/certs/myca.crt"
ca_validity_days: 3650
cert_validity_days: 365