---
- name: Get system architecture
  set_fact:
    cli_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Get latest stable Cilium CLI version
  uri:
    url: https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
    return_content: yes
  register: cilium_cli_version

- name: Set trimmed Cilium CLI version
  set_fact:
    cilium_cli_ver: "{{ cilium_cli_version.content | trim }}"

- name: Download Cilium CLI binary
  get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_ver }}/cilium-linux-{{ cli_arch }}.tar.gz"
    dest: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
    mode: '0644'

- name: Download Cilium CLI checksum
  get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_ver }}/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
    dest: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
    mode: '0644'

- name: Verify checksum
  command: sha256sum --check /tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum
  args:
    chdir: /tmp

- name: Extract Cilium CLI to /usr/local/bin
  become: true
  unarchive:
    src: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'

- name: Clean up downloaded files
  file:
    path: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz{{ item }}"
    state: absent
  loop:
    - ""
    - ".sha256sum"

- name: Check if Cilium is already installed
  command: cilium status
  register: cilium_status
  ignore_errors: yes
  changed_when: false

- name: Install Cilium (if not already installed)
  command: "cilium install --version {{ cilium_version }}"
  when: cilium_status.rc != 0