apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "{{ hostvars[groups['kube-apiserver-haproxy'][0]].ansible_default_ipv4.address }}:{{ kubernetes_default_port }}"
networking:
  podSubnet: "{{ kubernetes_network }}"
  serviceSubnet: "{{ kubernetes_service_network }}"
etcd:
  external:
    endpoints:
    {% for host in groups['etcd-nodes'] %}
    - https://{{ hostvars[host].ansible_default_ipv4.address }}:2379
    {% endfor %}
    caFile: /etc/etcd/ca.crt
    certFile: /etc/etcd/client.crt
    keyFile: /etc/etcd/client.key
