---

- name: Save firewall-rules
  ansible.builtin.shell:
    cmd: "/usr/sbin/netfilter-persistent save"
    # creates: '/etc/iptables/rules.v4'

- name: Reload firewall-rules
  ansible.builtin.systemd:
    name: iptables
    state: restarted
    daemon_reload: true
    enabled: true
